export const ADD_RECIPE = 'ADD_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_FAVOURITE_RECIPE = 'GET_FAVOURITE_RECIPE';
export const ADD_FAVOURITE_RECIPE = 'ADD_FAVOURITE_RECIPE';
export const REVIEW_RECIPE = 'REVIEW_RECIPE';
export const REMOVE_FAVOURITE_RECIPE = 'REMOVE_FAVOURITE_RECIPE';
export const UPVOTE_RECIPE = 'UPVOTE_RECIPE';
export const DONWVOTE_RECIPE = 'DONWVOTE_RECIPE';

export const USER_LOGOUT = 'USER_LOGOUT';



