export const ADD_RECIPE = 'ADD_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_FAVOURITE_RECIPE = 'GET_FAVOURITE_RECIPE';
export const ADD_FAVOURITE_RECIPE = 'ADD_FAVOURITE_RECIPE';
export const REVIEW_RECIPE = 'REVIEW_RECIPE';
export const REMOVE_FAVOURITE_RECIPE = 'REMOVE_FAVOURITE_RECIPE';
export const UPVOTE_RECIPE = 'UPVOTE_RECIPE';
export const DONWVOTE_RECIPE = 'DONWVOTE_RECIPE';
export const REQUEST_ADD_RECIPE = 'REQUEST_ADD_RECIPE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const LOGIN_ERRORS = 'LOGIN_ERRORS';
export const USER_PROFILE = 'USER_PROFILE';
export const MY_RECIPES = 'MY_RECIPES';
export const MY_RECIPES_ERROR = 'MY_RECIPES_ERROR';
export const USER_SIGNUP = 'USER_SIGNUP';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
export const SIGNUP_ERRORS = 'SIGNUP_ERRORS';





